# R-Series 6-DoF Arm with Gripper
version: 1.0
families: ["Rosie"]
names: ["J1_base", "J2_shoulder", "J3_elbow", "J4_wrist1", "J5_wrist2", "J6_wrist3"]
hrdf: "../../arms/config/hrdf/A-2580-06G.hrdf"

gains:
  default: "../../arms/config/gains/A-2580-06.xml"
  gripper: "../../arms/config/gains/A-2255-01.xml"

user_data:
  # Default seed positions for doing inverse kinematics
  ik_seed_pos: [0.01, 1.0, 1.5, 1.5, -1.5, 0.01]

  # Gripper specific settings
  has_gripper: true
  gripper_open_effort: 1
  gripper_close_effort: -5

  # Time taken for a steady motion to the home position
  homing_duration: 5 # seconds

  # Online trajectory delay to smooth out controller motion.  A shorter 
  # delay will make a trajectory more response, and longer delay will make 
  # the trajectory smooother.
  delay_time: 0.5 # seconds

  # Displacements of the mobile device are scaled by these value to give  
  # displacement of the end-effector
  xyz_scale: [ 0.375, 0.375, 0.75 ]   # [ x, y, z ]

plugins:
  - type: GravityCompensationEffort
    name: gravComp
    enabled: true
    ramp_time: 5

  - type: DynamicsCompensationEffort
    name: dynamicsComp
    enabled: true
    ramp_time: 5

  # Kits with a gas spring need to add a shoulder compensation torque.
  # It should be around -7 Nm for most kits, but it may need to be tuned
  # for your specific setup.
  - name: 'gasSpringCompensation'
    type: EffortOffset
    enabled: true
    ramp_time: 5
    offset: [0, -7, 0, 0, 0, 0]